const AG_ADAPTER_DEFAULT = {
  fieldSelector: "input, select, textarea",
  isExcluded: () => false,
  getFieldId: () => null,
  getFieldLabel: () => null,
  isTextField: null,
  isDropdown: () => false,
  isCheckbox: null,
  isMultiselect: () => false,
  fillTextField: null,
  fillDropdown: null,
  fillSelect: null,
  fillCheckbox: null,
  getDropdownValue: (el) => (el.textContent || "").trim(),
  getCheckboxChecked: null,
  getRadioValue: null,
  getRadioGroup: null,
  getRadioOptionText: null,
  attachDropdownListener: () => {},
  attachCheckboxListener: () => {},
  attachTextCaptureListener: () => false,
  getCheckboxGroupMembers: null,
  emptyPlaceholderValues: [],
  instanceFields: [],
  getJobId: () => null,
  getInstanceId: () => null,
  shadowContainerSelector: null,
  waitForReady: null,
  gateFillOnVisibility: false,
  suppressRefillOnRerender: false,
  getHighlightSelector: null,
  getTextValue: (el) => el.value,
  synthesizeValue: null,
  prefillPass: null
};
